---
# "Prepare to install Redis"
- include: redis_deb.yml tags=redis
  when: ansible_distribution in [ 'Ubuntu' ]

# "Install Redmon dashboard"
- include: redmon.yml tags=redmon
  when: with_redmon and ansible_distribution in [ 'Ubuntu' ]
