---

- name: "redis | point to latest Redis packages from Ubuntu PPA"
  apt_repository: repo='ppa:rwky/redis'

- name: "redis | install service"
  apt: name={{ redis.deb.package }} state=latest update-cache=yes

- name: "redis | bind service to all interfaces"
  action: lineinfile dest=/etc/redis/redis.conf state=present regexp="^#?bind" line="#bind 127.0.0.1"
  notify:
    - "Restart Redis"

- name: "redis | ensure service is running"
#  sudo: yes
  service: name={{ redis.deb.service }} enabled=yes
