---

- name: "Install Redmon dependencies"
# sudo: yes
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items: redmon.deb.dependencies

- name: "Install Redmon gems"
  action: gem name={{ item }} state=present user_install=no #executable=/usr/bin/gem1.9.1
  with_items: redmon.gems

- name: "Install Redmon runit script"
  template: src=redmon-runit.sh dest=/etc/service/{{ redmon.service }}/run  owner=root group=root mode=0755

- name: "Ensure Redis server is running"
  action: service name={{ redmon.service }} state=started
