---

- name: "redmon | install dependencies"
# sudo: yes
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items: redmon.deb.dependencies

- name: "redmon | install required gems"
  action: gem name={{ item }} state=present user_install=no #executable=/usr/bin/gem1.9.1
  with_items: redmon.gems

- name: "redmon | create runit service-directory"
  file: dest=/etc/service/{{ redmon.service }}  owner=root group=root state=directory

- name: "redmon | install runit run-script"
  template: src=redmon-runit.sh dest=/etc/service/{{ redmon.service }}/run  owner=root group=root mode=0755

- name: "redmon | install runit status-script"
  template: src=redmon-runit.j2 dest=/etc/init.d/{{ redmon.service }} owner=root group=root mode=0755

- name: "redmon | ensure service is running"
  service: name={{ redmon.service }} state=started
  #service: name={{ redmon.service }} pattern={{ redmon.bin }} enabled=yes
